### ISSUE TITLE
single-run mode

### ISSUE THREAD

**Issue by krotscheck** [davglass/registry-static#67]
Following up #66 - the next thing I'd like to contribute is a single-run mode, i.e. a mode that brings the mirror up-to-date, and then exits with status 0. The reason is that our mirroring is actually a two-step process: Update the filesystem on a privileged host, and then pushing the changes to the AFS master disks (aka `vos release`). This latter part is way easier for us if we can guarantee that our filesystem is consistent, and will not change during the - perhaps slow - process of updating the master.

After digging a bit, it seems that the best place to start is by taking advantage of the wait() hook in the follow library. Surfacing this up through follow-registry, I can call process.exit() when it is triggered, assuming the appropriate commandline option (assuming `--single-run`) is passed.

Do you have any comments on this? Perhaps suggestions on how to approach it differently?

**Comment by bengl** [comment]
Rather than exiting, would *pausing* do the trick? I.e. don't write to the fs or blob-store while in "paused" mode.

If that isn't suitable, then you can also wrap some process management around registry-static, paying attention to the lag (which you can get at via the web interface or the telnet REPL).

And if that's not good enough, a PR implementing something like `--single-run` would definitely be considered. They way I'd implement it is to exit when the lag is zero, perhaps checking once done processing each module. I'd maybe bikeshed the naming of it though. Perhaps `--exit-once-synced`?

**Comment by krotscheck** [comment]
I don't think pause is an option. That feels like I'd have to write code to do kerberos key management, authentication, and all kinds of other fiddly things. For reference, here's the cron job we use to sync everything up:

https://review.openstack.org/#/c/235617/18/modules/openstack_project/templates/npm-mirror-update.sh

When you say 'paying attention to the lag', you're referring to the `latestSeq` and `sequence` properties in `/-/index.json`, yes? In other words, kill the process when both of those are the same?

**Comment by bengl** [comment]
> When you say 'paying attention to the lag', you're referring to the latestSeq and sequence properties in /-/index.json, yes? In other words, kill the process when both of those are the same?

Yep. `lag = latestSeq - sequence`. You can also get those numbers from the web api (`--httpport=1234` and then `http://mydomain:1234/stats.json`) or the telnet repl (`--replport=1234` and then telnet into it, and have a look at `process.registryStaticStats`).

**Comment by krotscheck** [comment]
Got it- if that's the case, I may even be able to do this as a hook beforeIndexJson hook. Or, well, add an afterIndexJson hook ;).

**Comment by krotscheck** [comment]
So, it turns out that I can use the afterAll hook, and just call process.exit() there. Thanks!
